#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine with Nginx /redirect_me page

ssh -i ~/.ssh/holberton ubuntu@34.74.113.207 'sudo apt-get update; sudo apt-get -y install nginx'
ssh -i ~/.ssh/holberton ubuntu@34.74.113.207 'echo "Holberton School" | sudo tee /var/www/html/index.html'
ssh -i ~/.ssh/holberton ubuntu@34.74.113.207 'sudo sed -i "/server_name _;/ a\ \trewrite ^\/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default'
ssh -i ~/.ssh/holberton ubuntu@34.74.113.207 'sudo systemctl restart nginx'
