#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine with 404 error

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html

redi_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$redi_str/" /etc/nginx/sites-available/default

error_str="Ceci n'est pas une page\n"
echo -e "$error_str" | sudo tee /var/www/html/404_error.html

error_str="server_name _;\n\terror_page 404 \/404_error.html;\n\tlocation = \/404_error.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$error_str/" /etc/nginx/sites-available/default

sudo service nginx restart
