#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process

case "$1" in
    start)
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
	;;
    stop)
	sudo kill "$(cat /var/run/my_process.pid)"
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;
    restart)
	sudo kill "$(cat /var/run/my_process.pid)"
	sudo rm /var/run/my_process.pid
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
esac
