#!/usr/bin/env bash
# This script displays numbers from 1 to 100 FizzBuzz challenge

n=1
while ((n <= 100)); do
    if ((n % 3 == 0 && n % 5 != 0))
    then
	echo "Fizz"
    elif ((n % 5 == 0 && n % 3 != 0))
    then
	echo "Buzz"
    elif ((n % 3 == 0 && n % 5 == 0))
    then
	echo "FizzBuzz"
    else
	echo $n
    fi
    n=$((n+1));
done
