#!/usr/bin/env bash
# This script gives you information about the "holbertonschool" file.

FILE_NAME="holbertonschool"

if [ -e "$FILE_NAME" ]
then
    echo "holbertonschool file exists"
    if [ -s "$FILE_NAME" ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f "$FILE_NAME" ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
