#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
# localhost resolves to 127.0.0.2 facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.aux
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.aux
sed -i "2i8.8.8.8 \tfacebook.com" ~/hosts.aux
cp -f ~/hosts.aux /etc/hosts
