#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user
# give nginx configuration file permissions to read-write
sudo chmod uo+rw /etc/nginx/nginx.conf

#modify config file to user nginx
sudo sed -i "1s/.*/user nginx;/" /etc/nginx/nginx.conf

# modify port listening nginx
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default

# Kill process using port 80
sudo pkill -o apache2

# restart server
su nginx -c "service nginx restart"
